# Generated by Django 3.0.3 on 2020-02-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200220_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='userd',
            new_name='user',
        ),
    ]
